# -*- coding: utf-8 -*-
"""stemming-and-lemmatization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7SyVacMCeCypUY7FxXTEj652Jh_POUJ
"""

!pip install -q nltk

# Step 1: Install NLTK (Google Colab usually has it pre-installed, but good practice)
# !pip install -q nltk

# Step 2: Import libraries and download necessary NLTK datasets
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download tokenizers and the WordNet lexical database
nltk.download('punkt')
nltk.download('punkt_tab')  # <-- This line fixes your LookupError
nltk.download('wordnet')

# Step 3: Initialize the stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Step 4: Define a sample sentence
sentence = "The feet of the runners were changing speeds during the race."

# Step 5: Tokenize the sentence into individual words
words = word_tokenize(sentence)

# Step 6: Apply both techniques and print the comparative results
print(f"{'Original Word':<15} | {'Stemmed (Porter)':<18} | {'Lemmatized (WordNet)':<20}")
print("-" * 60)

for word in words:
    # Stemming
    stemmed = stemmer.stem(word)
    # Lemmatization (defaults to noun classification unless specified)
    lemmatized = lemmatizer.lemmatize(word)

    print(f"{word:<15} | {stemmed:<18} | {lemmatized:<20}")

